import Link from 'next/link';
import { ArrowRight, Clock3, MapPin, Music2, Star, Utensils } from 'lucide-react';

/* A home conduz o visitante do desejo à ação: conhecer o cardápio ou reservar. */
export default function Home() {
  return <main>
    {/* Hero com proposta direta e imagem real do restaurante. */}
    <section className="hero" aria-labelledby="hero-title"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">O sabor que reúne BH</p><h1 id="hero-title">Peixe bem servido.<br /><em>Momento bem vivido.</em></h1><p className="hero-lead">Porções generosas, cerveja gelada e aquele clima leve de Santa Inês — todos os dias, do almoço ao encontro com os amigos.</p><div className="actions"><Link className="button button-primary" href="/cardapio">Ver cardápio <ArrowRight size={18} /></Link><a className="button button-ghost" href="https://wa.me/5531991536420" target="_blank" rel="noopener noreferrer">Reservar mesa</a></div><div className="hero-facts"><span><Clock3 size={18} /> Aberto todos os dias</span><span><MapPin size={18} /> Santa Inês, BH</span></div></div><div className="hero-visual"><img src="/images/prato.jpg" alt="Prato de peixe servido no Chico do Peixe" width="900" height="700" fetchPriority="high" /><div className="rating-card"><Star size={18} fill="currentColor" /><strong>22,9 mil</strong><span>seguidores no Instagram</span></div></div></div></section>
    {/* Benefícios inspirados nos destaques públicos do Instagram. */}
    <section className="section" aria-labelledby="experiencias-title"><div className="container"><p className="eyebrow">Tem sempre um motivo para vir</p><div className="section-heading"><h2 id="experiencias-title">Do almoço ao happy hour</h2><p>Uma casa feita para comer bem, celebrar e ficar à vontade.</p></div><div className="feature-grid"><article className="feature-card"><Utensils /><span>01</span><h3>Almoço caprichado</h3><p>Peixes, porções e acompanhamentos para dividir — ou não.</p></article><article className="feature-card featured"><Music2 /><span>02</span><h3>Música & jogos</h3><p>Agenda especial e transmissões para animar a semana.</p></article><article className="feature-card"><Star /><span>03</span><h3>Seu aniversário</h3><p>Um espaço descontraído para reunir toda a turma.</p></article></div></div></section>
    {/* Ambiente familiar com acesso à história da casa. */}
    <section className="story-section"><div className="container story-grid"><div className="story-image"><img src="/images/playground.png" alt="Espaço com playground do Chico do Peixe" width="1500" height="741" loading="lazy" /></div><div className="story-copy"><p className="eyebrow">Para toda a família</p><h2>Você chega pela comida.<br />Fica pelo clima.</h2><p>Ambiente amplo, Wi-Fi liberado e playground para a garotada. Aqui, cada detalhe convida a aproveitar sem pressa.</p><Link className="text-link" href="/sobre">Conheça a nossa história <ArrowRight size={17} /></Link></div></div></section>
    {/* Chamada final reduz o esforço para converter. */}
    <section className="visit-section"><div className="container visit-inner"><div><p className="eyebrow light">Hoje combina com Chico</p><h2>Sua mesa está esperando.</h2></div><div className="actions"><a className="button button-light" href="https://wa.me/5531991536420" target="_blank" rel="noopener noreferrer">Falar no WhatsApp</a><Link className="button button-outline-light" href="/contato">Como chegar</Link></div></div></section>
  </main>;
}
